<?php
$track_ways = Track::getTrackWays();
?>
<?= $this->partial('/common/header.phtml', $this) ?>
<table class="table">
    <thead>
        <tr>
            <td>ID</td>
            <td>網址</td>
            <td>追查內容</td>
            <td>最近變動時間</td>
            <td>上次追查時間</td>
            <td>追查頻率</td>
            <td>數值</td>
            <td>追蹤中</td>
            <td>動作</td>
        </tr>
    </thead>
    <tbody>
    <?php foreach (Track::search(1) as $track) { ?>
    <tr id="tr-<?= $track->id ?>">
        <td><?= $track->id ?></td>
        <td>
            <div><a href="/?id=<?= $track->id ?>#track-log"><?= $this->escape($track->title) ?></a></div>
            <small><a href="<?= $this->escape($track->url) ?>"><?= $this->escape(substr($track->url, 0, 32)) ?></a></small>
        </td>
        <td>
            <span title="<?= $this->escape($track->getTrackContent()) ?>"><?= $this->escape($track_ways[$track->getWay()]) ?></span>
        </td>

        <td><?= $this->partial('/helper/counttime.phtml', arraY('time' => $track->getLatestLog()->time)) ?></td>
        <td><?= $this->partial('/helper/counttime.phtml', arraY('time' => $track->tracked_at)) ?></td>
        <td><?= $this->Escape(Track::getTrackPeriods()[$track->track_period]) ?></td>
        <td>
            <?php $log = json_decode($track->getLatestLog()->content) ?>
            <div title="<?= $this->escape(json_encode($log, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)) ?>">
                HTTP:<?= intval($log->http_code) ?><br>
                status: <?= $this->escape($log->status) ?>
            </div>
        </td>
        <td>
            <form method="post" action="/index/toggletrack?id=<?= $track->id ?>">
                <input type="hidden" name="sToken" value="<?= $this->escape($this->sToken) ?>">
                <input type="hidden" name="return_to" value="tr-<?= $track->id ?>">
                <button type="submit"><?= ($track->isTrackBy($this->user)) ? '追蹤中' : '未追蹤' ?></button>
            </form>
        </td>
        <td>
            <a href="/?id=<?= $track->id ?>#edit-track">修改</a>
            <a href="/index/check?id=<?= $track->id ?>">立刻檢查</a>
        </td>
    </tr>
    <?php } ?>
    </tbody>
</table>
<form method="post" action="<?= $this->track ? "/index/edittrack?id={$this->track->id}" : "/index/addtrack" ?>" id="edit-track">
    <input type="hidden" name="sToken" value="<?= $this->escape($this->sToken) ?>">
    描述：<input type="text" name="title" value="<?= $this->escape($this->track->title) ?>"></br>
    網址: <input type="text" name="url" value="<?= $this->Escape($this->track->url) ?>"><br>
    追蹤頻率：<select name="track_period">
        <?php foreach (Track::getTrackPeriods() as $id => $name) { ?>
        <option value="<?= $id ?>"<?= ($this->track and $this->track->track_period == $id) ? ' selected="selected"' : '' ?>><?= $this->escape($name) ?></option>
        <?php } ?>
    </select>
    追蹤方式：<select name="track-way">
        <?php foreach (Track::getTrackWays() as $id => $name) { ?>
        <option value="<?= $id ?>"<?= ($this->track and $this->track->getWay() == $id) ? ' selected="selected"' : '' ?>><?= $this->escape($name) ?></option>
        <?php } ?>
    </select><br>
    追蹤內容：<input type="text" name="track-content" value="<?= $this->escape($this->track ? $this->track->getTrackContent() : '') ?>"><br>
    跟隨302、301：<select name="follow_301">
        <option value="0">不跟隨</option>
        <option value="1" <?= ($this->track and $this->track->getFollow301()) ? ' selected="selected"' : '' ?>>跟隨</option>
    </select>

    <button type="submit" id="preview">預覽</button>
    <button type="submit">送出</button>
    <div id="preview-result"></div>
</form>
<script>
$('#preview').click(function(e){
    e.preventDefault();
    $.get('/index/preview?url=' + encodeURIComponent($('[name="url"]').val()) + '&track_content=' + encodeURIComponent($('[name="track-content"]').val()) , function(ret){
        $('#preview-result').text(JSON.stringify(ret));
    }, 'json');
});
</script>
<div id="preview-result"></div>
<?php if ($this->track) { ?>
<hr>
<h1>追蹤人</h1>
<ol id="track-user">
    <?php foreach (TrackUser::search(array('track_id' => $this->track->id)) as $track_user) {?>
    <li><?= $this->escape($track_user->user->user_name) ?></li>
    <?php } ?>
</ol>
<form method="post" action="/index/toggletrack?id=<?= $this->track->id ?>">
    <input type="hidden" name="sToken" value="<?= $this->escape($this->sToken) ?>">
    <button type="submit"><?= ($this->track->isTrackBy($this->user)) ? '取消追蹤' : '我要追蹤' ?></button>
</form>
<hr>
<h1>變動紀錄</h1>
<ol id="track-log">
    <?php foreach (TrackLog::search(array('track_id' => $this->track->id))->order('time DESC') as $track_log) { ?>
    <li><?= date('c', $track_log->time) ?>: <code><?= $this->escape(Helper::decode_utf8(urldecode($track_log->content))) ?></code></li>
    <?php } ?>
</ol>
<?php } ?>
<?= $this->partial('/common/footer.phtml', $this) ?>
