<?= $this->partial('/common/header.phtml', $this) ?>
<table class="table">
    <thead>
        <tr>
            <td>ID</td>
            <td>網址</td>
            <td>追查內容</td>
            <td>最近變動時間</td>
            <td>上次追查時間</td>
            <td>追查頻率</td>
            <td>數值</td>
            <td>動作</td>
        </tr>
    </thead>
    <tbody>
    <?php foreach (Track::search(1) as $track) { ?>
    <tr>
        <td><?= $track->id ?></td>
        <td>
            <h3><?= $this->escape($track->title) ?></h3>
            <small><?= $this->escape($track->url) ?></small>
        </td>
        <td><?= $this->escape($track->options) ?></td>
        <td><?= $this->partial('/helper/counttime.phtml', arraY('time' => $track->getLatestLog()->time)) ?></td>
        <td><?= $this->partial('/helper/counttime.phtml', arraY('time' => $track->tracked_at)) ?></td>
        <td><?= $this->Escape(Track::getTrackPeriods()[$track->track_period]) ?></td>
        <td><?= $this->escape($track->getLatestLog()->content) ?></td>
        <td>
            <a href="/?id=<?= $track->id ?>">修改</a>
        </td>
    </tr>
    <?php } ?>
    </tbody>
</table>
<form method="post" action="<?= $this->track ? "/index/edittrack?id={$this->track->id}" : "/index/addtrack" ?>">
    <input type="hidden" name="sToken" value="TODO">
    描述：<input type="text" name="title" value="<?= $this->escape($this->track->title) ?>"></br>
    網址: <input type="text" name="url" value="<?= $this->Escape($this->track->url) ?>"><br>
    追蹤頻率：<select name="track_period">
        <?php foreach (Track::getTrackPeriods() as $id => $name) { ?>
        <option value="<?= $id ?>"<?= ($this->track and $this->track->track_period == $id) ? ' selected="selected"' : '' ?>><?= $this->escape($name) ?></option>
        <?php } ?>
    </select>
    追蹤方式：<select name="track-way">
        <?php foreach (Track::getTrackWays() as $id => $name) { ?>
        <option value="<?= $id ?>"<?= ($this->track and $this->track->getWay() == $id) ? ' selected="selected"' : '' ?>><?= $this->escape($name) ?></option>
        <?php } ?>
    </select><br>
    追蹤內容：<input type="text" name="track-content" value="<?= $this->escape($this->track ? $this->track->getTrackContent() : '') ?>">
    <button type="submit">送出</button>
</form>
<?php if ($this->track) { ?>
<ol>
    <?php foreach (TrackLog::search(array('track_id' => $this->track->id))->order('time DESC') as $track_log) { ?>
    <li><?= date('c', $track_log->time) ?>: <code><?= $this->escape($track_log->content) ?></code></li>
    <?php } ?>
</ol>
<?php } ?>
<?= $this->partial('/common/footer.phtml', $this) ?>
