<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title><?= $this->escape($this->title) ?>內容追蹤</title>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.2.2/bootstrap.min.js"></script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.2.2/css/bootstrap.css">
<?php if (getenv('GOOGLEANALYTICS_ACCOUNT')) { ?>
<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', <?= json_encode(getenv('GOOGLEANALYTICS_ACCOUNT')) ?>]);
_gaq.push(['_trackPageview']);

(function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
<?php } ?>
</head>
<body>
<div class="navbar">
    <div class="navbar-inner">
        <a class="brand" href="/">內容追蹤</a>
        <ul class="nav">
            <li>
            <a href="/">首頁</a>
            </li>
            <?php if ($this->user) { ?>
            <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Hi! <?= $this->escape($this->user->user_name) ?><b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li class="divider"></li>
                <li><a href="/login/logout">登出</a></li>
            </ul>
            </li>
            <?php } else { ?>
            <li>
            <a href="/login/google">登入</a>
            </li>
            <?php } ?>
        </ul>
    </div>
</div>
<div class="container-fluid">
    <div class="row-fluid">
